### ISSUE TITLE
bootstrap_models.py is broken

### ISSUE THREAD

**Issue by chrishart0** [iGavroche/BrainChulo#79]
Just cloned your repo down. Tried following through the readme and ran into an issue with bootstrap_models.py

```
 $ python bootstrap_models.py

NOTE: You can change the default downloaded model by passing an additional argument:bootstrap_models.py [hugging-face-llm-model-name] [hugging-face-embeddings-model-name]
Your choices:
MODEL: openlm-research/open_llama_3b
EMBEDDINGS MODEL: sentence-transformers/all-MiniLM-L6-v2

Downloading model sentence-transformers/all-MiniLM-L6-v2 to ./models/sentence-transformers/all-MiniLM-L6-v2
Please note that if model is large this may take a while.
Traceback (most recent call last):
  File "/media/chris/LLM Drive/BrainChulo/bootstrap_models.py", line 58, in <module>
    main(model, embeddings)
  File "/media/chris/LLM Drive/BrainChulo/bootstrap_models.py", line 32, in main
    _download_if_not_exists(embeddings_model)
  File "/media/chris/LLM Drive/BrainChulo/bootstrap_models.py", line 19, in _download_if_not_exists
    process.check_returncode()
  File "/usr/lib/python3.11/subprocess.py", line 502, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['python3', 'download-model.py', 'sentence-transformers/all-MiniLM-L6-v2', '--output', './models']' returned non-zero exit status 1.
```

### System Info
OS: Ubuntu 22.04
Python Version: 3.11.4

**Comment by hugothomel** [comment]
Hello there! Thanks for signaling this issue, we're looking into it!

**Comment by paolorechia** [comment]
Hi, thanks for reporting it. It looks like the script needs to log more info on failure, we cannot tell from the current logs what the issue is.

@chrishart0 Would you be willing to try again if we added more logs here?

**Comment by chrishart0** [comment]
Yes

**Comment by hugothomel** [comment]
So I created a new branch called _fix-bootstrap_  that I suggest you pull. I noticed we had a dependencies issue when installing the requirements, which allowed for a reproduction of your error if not acted upon. Can you try running bash setup.sh again and tell us if it works?
